name: goodbye Rust CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'goodbye-rust/**'
      - '.github/workflows/goodbye-rust-ci.yml'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        uses: clechasseur/rs-cargo@v2
        with:
          command: test
          args: --verbose --manifest-path crates/goodbye-rust/Cargo.toml
      - name: Build
        uses: clechasseur/rs-cargo@v2
        with:
          command: build
          args: --verbose --release --manifest-path crates/goodbye-rust/Cargo.toml
