name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      goodbye-rust--tag_name: ${{ steps.release.outputs.goodbye-rust--tag_name}}
      goodbye-rust--release_created: ${{ steps.release.outputs.goodbye-rust--release_created}}
      hello-rust--tag_name: ${{ steps.release.outputs.hello-rust--tag_name}}
      hello-rust--release_created: ${{ steps.release.outputs.hello-rust--release_created}}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"


  release-goodbye-rust:
    if: ${{needs.release-please.outputs.goodbye-rust--release_created}}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        uses: clechasseur/rs-cargo@v2
        with:
          command: test
          args: --verbose --manifest-path goodbye-rust/Cargo.toml
      - name: Build
        uses: clechasseur/rs-cargo@v2
        with:
          command: build
          args: --verbose --release --manifest-path goodbye-rust/Cargo.toml --target x86_64-unknown-linux-gnu
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.goodbye-rust--tag_name }} goodbye-rust/target/x86_64-unknown-linux-gnu/release/goodbye_rust

  release-hello-rust:
    if: ${{needs.release-please.outputs.hello-rust--release_created}}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        uses: clechasseur/rs-cargo@v2
        with:
          command: test
          args: --verbose --manifest-path hello-rust/Cargo.toml
      - name: Build
        uses: clechasseur/rs-cargo@v2
        with:
          command: build
          args: --verbose --release --manifest-path hello-rust/Cargo.toml --target x86_64-unknown-linux-gnu
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.hello-rust--tag_name }} hello-rust/target/x86_64-unknown-linux-gnu/release/hello_rust
